/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import backend.ComboItem;
import backend.ConnectionManager;
import backend.ProductDAO;
import backend.ProductDAO.StockBatchDetails;
import backend.StockBatchItem;
import com.formdev.flatlaf.FlatDarkLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Nethula
 */
public class BillingSystem extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public BillingSystem() {
        initComponents();
        loadCustomersIntoComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        barcodeTextField = new javax.swing.JTextField();
        barcodeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        QtyUpdateDetails = new javax.swing.JButton();
        StockUpdateDetails = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        StockComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ProductNameLabel = new javax.swing.JLabel();
        StockDateLabel = new javax.swing.JLabel();
        RemAfterBuyLabel = new javax.swing.JLabel();
        UnitPriceLabel = new javax.swing.JLabel();
        AddEntryButton = new javax.swing.JButton();
        barcodeLabel1 = new javax.swing.JLabel();
        CustomerComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        QtySpinner = new javax.swing.JSpinner();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Title.setText("Billing System");

        BackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BackButton.setText("← Back ");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Barcode", "Product Name", "Unit Price", "Qty", "Amount", "Del"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(450, 70));
        jScrollPane1.setViewportView(jTable1);

        barcodeTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barcodeTextField.setToolTipText("Type the product barcode here");

        barcodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barcodeLabel.setText("Product Barcode");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Qty");

        QtyUpdateDetails.setText("Update Details");
        QtyUpdateDetails.setPreferredSize(new java.awt.Dimension(75, 25));
        QtyUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyUpdateDetailsActionPerformed(evt);
            }
        });

        StockUpdateDetails.setText("Update Details");
        StockUpdateDetails.setPreferredSize(new java.awt.Dimension(75, 25));
        StockUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockUpdateDetailsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Stock");

        StockComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Current Total: Rs. 0.00");
        jLabel6.setToolTipText("");

        ProductNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProductNameLabel.setText("Product Name:");

        StockDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StockDateLabel.setText("Stock Date:");

        RemAfterBuyLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemAfterBuyLabel.setText("Remaining (After Buy):");

        UnitPriceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UnitPriceLabel.setText("Unit Price:");

        AddEntryButton.setText("Add Entry");
        AddEntryButton.setPreferredSize(new java.awt.Dimension(75, 25));
        AddEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryButtonActionPerformed(evt);
            }
        });

        barcodeLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barcodeLabel1.setText("Customer ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Given Money:");

        jButton6.setText("Add Entry");
        jButton6.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Change: Rs. 0.00");
        jLabel12.setToolTipText("");

        jButton7.setText("Calculate");
        jButton7.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        QtySpinner.setPreferredSize(new java.awt.Dimension(64, 26));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.01d));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(barcodeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barcodeTextField)
                            .addComponent(barcodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProductNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StockDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RemAfterBuyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(UnitPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddEntryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QtyUpdateDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QtySpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1)
                            .addComponent(StockComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StockUpdateDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barcodeLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barcodeLabel1)
                        .addComponent(CustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(barcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockUpdateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(QtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QtyUpdateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UnitPriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemAfterBuyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEntryButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        DashBoard dashboard = new DashBoard();  // or any other JFrame
        dashboard.setVisible(true);

        // Close the current frame
        this.dispose(); // closes the frame that this button is part of
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void StockComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockComboBoxActionPerformed

        StockBatchItem selected = (StockBatchItem) StockComboBox.getSelectedItem();

        if (selected != null) {
            int availableQty = selected.getRemainingItems(); // this must be stored in StockBatchItem

            // Create a new Spinner model with updated max quantity
            SpinnerNumberModel qtyModel = new SpinnerNumberModel(1, 1, availableQty, 1);
            QtySpinner.setModel(qtyModel);
        }
    }//GEN-LAST:event_StockComboBoxActionPerformed

    private void StockUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockUpdateDetailsActionPerformed
        // TODO add your handling code here:
        String barcode = barcodeTextField.getText();
        ProductDAO dao = new ProductDAO();
        Integer productId = dao.getProductIdByBarcode(barcode);

        if (productId != null) {
            List<StockBatchItem> stockBatches = dao.getStockBatchesByProductId(productId);

            StockComboBox.removeAllItems(); // Clear previous items

            if (stockBatches.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No stock available for this product.", "Stock Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (StockBatchItem item : stockBatches) {
                    StockComboBox.addItem(item);
                }
            }
        }
    }//GEN-LAST:event_StockUpdateDetailsActionPerformed

    private void QtyUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyUpdateDetailsActionPerformed
        // TODO add your handling code here:
        // 1. Get selected stock batch from combo box
        StockBatchItem selectedBatch = (StockBatchItem) StockComboBox.getSelectedItem();
        if (selectedBatch == null) {
            JOptionPane.showMessageDialog(this, "Please select a stock batch first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Get quantity from spinner
        int selectedQty = (int) QtySpinner.getValue();

        // 3. Get stock batch details from DAO (product name, unit price, stock date, remaining)
        ProductDAO dao = new ProductDAO();
        StockBatchDetails details = dao.getStockBatchDetailsById(selectedBatch.getBatchId());

        if (details == null) {
            JOptionPane.showMessageDialog(this, "Could not find stock batch details.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Calculate remaining after buy
        int remainingAfterBuy = details.remainingItems - selectedQty;

        // 5. Update labels
        ProductNameLabel.setText("Product Name: " + details.productName);
        UnitPriceLabel.setText("Unit Price: " + details.unitPrice);
        StockDateLabel.setText("Stock Date: " + details.stockDate);
        RemAfterBuyLabel.setText("Remaining (After Buy): " + remainingAfterBuy);
    }//GEN-LAST:event_QtyUpdateDetailsActionPerformed

    public void loadCustomersIntoComboBox() {
        String sql = "SELECT customer_id, name FROM customer";

        try (Connection conn = ConnectionManager.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery()) {
        
            CustomerComboBox.removeAllItems();
            CustomerComboBox.addItem(new ComboItem(0, "Select Customer"));
            while (rs.next()) {
                int id = rs.getInt("customer_id");
                String name = rs.getString("name");
                System.out.println("→ " + id + ": " + name);
                CustomerComboBox.addItem(new ComboItem(id, "[" + id + "] " + name ));
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading Customers: " + e.getMessage());
        }
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();
        
        /* DB Fetch for */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystem().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEntryButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<ComboItem> CustomerComboBox;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JSpinner QtySpinner;
    private javax.swing.JButton QtyUpdateDetails;
    private javax.swing.JLabel RemAfterBuyLabel;
    private javax.swing.JComboBox<StockBatchItem> StockComboBox;
    private javax.swing.JLabel StockDateLabel;
    private javax.swing.JButton StockUpdateDetails;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UnitPriceLabel;
    private javax.swing.JLabel barcodeLabel;
    private javax.swing.JLabel barcodeLabel1;
    private javax.swing.JTextField barcodeTextField;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
