/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import backend.ConnectionManager;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import backend.ComboItem;


/**
 *
 * @author Nethula
 */
public class UpdateCustomer extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public UpdateCustomer() {
        initComponents();
        loadGendersIntoComboBox();
        loadCustomersIntoComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        customerNameBar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        phoneNumberBar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        birthYearBar = new javax.swing.JTextField();
        emailBar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        customerCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Change Customer Details");
        jLabel1.setToolTipText("");

        customerNameBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customerNameBar.setToolTipText("Enter your username in this input box");
        customerNameBar.setPreferredSize(new java.awt.Dimension(71, 25));
        customerNameBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameBarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Customer Name*");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Update Customer");
        jButton1.setToolTipText("");
        jButton1.setPreferredSize(new java.awt.Dimension(75, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        phoneNumberBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneNumberBar.setToolTipText("Enter your username in this input box");
        phoneNumberBar.setPreferredSize(new java.awt.Dimension(71, 25));
        phoneNumberBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberBarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Phone Number");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Email");

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("← Back ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Birth Year");

        genderCombo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        genderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Gender*");

        birthYearBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        birthYearBar.setToolTipText("Enter your username in this input box");
        birthYearBar.setPreferredSize(new java.awt.Dimension(71, 25));
        birthYearBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthYearBarActionPerformed(evt);
            }
        });

        emailBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailBar.setToolTipText("Enter your username in this input box");
        emailBar.setPreferredSize(new java.awt.Dimension(71, 25));
        emailBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Select Customer");

        customerCombo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(customerNameBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phoneNumberBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emailBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(genderCombo, 0, 648, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(birthYearBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(customerCombo, 0, 648, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthYearBar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameBarActionPerformed

    private void phoneNumberBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberBarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ComboItem customer = (ComboItem) customerCombo.getSelectedItem();
        String name = customerNameBar.getText();
        String phonenum = phoneNumberBar.getText();
        String email = emailBar.getText();
        String birthyr = birthYearBar.getText();
        ComboItem gender = (ComboItem) genderCombo.getSelectedItem();
        
        System.out.println("Customer ID: " + customer.getValue());
        System.out.println("Name: " + name);
        System.out.println("Phone Number: " + phonenum);
        System.out.println("Email: " + email);
        System.out.println("Birth Year: " + birthyr);
        System.out.println("Gender ID: " + gender.getValue());
        
        if(customer.getValue() != 0 && gender.getValue() != 0){
            String sql = "UPDATE customer SET name = ?, phone = ?, email = ?, birth_year = ?, gender_gender_id = ? WHERE customer_id = ?";
            try (Connection conn = ConnectionManager.getConnection();
                PreparedStatement ps = conn.prepareStatement(sql)) {

                ps.setString(1, name);
                ps.setString(2, phonenum);
                ps.setString(3, email);
                ps.setInt(4, Integer.parseInt(birthyr));
                ps.setInt(5, gender.getValue());
                ps.setInt(6, customer.getValue());

                int rows = ps.executeUpdate();
                System.out.println("Customer Successfully Updated!");
                JOptionPane.showMessageDialog(null, "Customer Successfully Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }else if(customer.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Please select a customer", "Insert Failed", JOptionPane.WARNING_MESSAGE);
        }else if(gender.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Please select a gender", "Insert Failed", JOptionPane.WARNING_MESSAGE);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DashBoard dashboard = new DashBoard();  // or any other JFrame
        dashboard.setVisible(true);

        // Close the current frame
        this.dispose(); // closes the frame that this button is part of
    }//GEN-LAST:event_jButton2ActionPerformed

    private void birthYearBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthYearBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthYearBarActionPerformed

    private void emailBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailBarActionPerformed

    private void genderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboActionPerformed

    private void customerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboActionPerformed
        // TODO add your handling code here:
        ComboItem selected = (ComboItem) customerCombo.getSelectedItem();
        if (selected != null) {
            int selectedId = selected.getValue();
            String selectedText = selected.getLabel();

            System.out.println("Selected ID: " + selectedId);
            System.out.println("Selected Text: " + selectedText);

            if (selectedId == 0) {
                System.out.println("User selected 'Select Customer' (default option)");
            } else {
                loadCustomerDetailsIntoBoxes(selectedId);
            }
        }
    }//GEN-LAST:event_customerComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCustomer().setVisible(true);
            }
        });
        
    }
    
    public void loadGendersIntoComboBox() {
        String sql = "SELECT gender_id, gender_name FROM gender";

        try (Connection conn = ConnectionManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {


            genderCombo.removeAllItems();
            genderCombo.addItem(new ComboItem(0, "Select Gender"));
            while (rs.next()) {
                int id = rs.getInt("gender_id");
                String name = rs.getString("gender_name");
                System.out.println("→ " + id + ": " + name);
                genderCombo.addItem(new ComboItem(id, name));
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading categories: " + e.getMessage());
        }
    }
    
    public void loadCustomersIntoComboBox() {
        String sql = "SELECT customer_id, name, birth_year FROM customer";

        customerCombo.removeAllItems();
        customerCombo.addItem(new ComboItem(0, "Select Customer"));
        try (Connection conn = ConnectionManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            // Loop through result set
            while (rs.next()) {
                int id = rs.getInt("customer_id");
                String name = rs.getString("name");
                String birthYear = rs.getString("birth_year");

                System.out.println("→ " + id + ": " + name);
                customerCombo.addItem(new ComboItem(id, "[" + id + "] " + name + " [" + birthYear + "]"));
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading customers: " + e.getMessage());
        }
    }
    

    public void loadCustomerDetailsIntoBoxes(int cusId) {
        String sql = "SELECT \n" +
                     "    c.customer_id,\n" +
                     "    c.name,\n" +
                     "    c.phone,\n" +
                     "    c.email,\n" +
                     "    c.birth_year,\n" +
                     "    g.gender_name,\n" +
                     "    g.gender_id\n" +
                     "FROM customer c\n" +
                     "JOIN gender g ON c.gender_gender_id = g.gender_id\n" +
                     "WHERE c.customer_id = ?;"
        ;

        try (Connection conn = ConnectionManager.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql)){
            ps.setInt(1, cusId);
            ResultSet rs = ps.executeQuery();

            if(rs.next()){
                String cusName = rs.getString("c.name");
                String cusPhone = rs.getString("c.phone");
                String cusEmail = rs.getString("c.email");
                int cusYr = rs.getInt("c.birth_year");
                String cusGenderName = rs.getString("g.gender_name");
                int cusGenderId = rs.getInt("g.gender_id");

                System.out.println("Customer ID: " + cusId);
                System.out.println("Customer Name: " + cusName);
                System.out.println("Customer Phone: " + cusPhone);
                System.out.println("Customer Email: " + cusEmail);
                System.out.println("Customer Birth Year: " + cusYr);
                System.out.println("Customer Gender Name: " + cusGenderName);
                System.out.println("Customer ID: " + cusGenderId);

                customerNameBar.setText(cusName);
                phoneNumberBar.setText(cusPhone);
                emailBar.setText(cusEmail);
                birthYearBar.setText(cusYr + "");
                genderCombo.setSelectedIndex(cusGenderId);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading customer details: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthYearBar;
    private javax.swing.JComboBox<ComboItem> customerCombo;
    private javax.swing.JTextField customerNameBar;
    private javax.swing.JTextField emailBar;
    private javax.swing.JComboBox<ComboItem> genderCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField phoneNumberBar;
    // End of variables declaration//GEN-END:variables
}
